
#- stat: path=/etc/php/7.1/fpm/php.ini
#  register: phpfpm

#- stat: path=/etc/php/7.1/cli/php.ini
#  register: phpcli

#- include: php.yml
#  when: phpcli.stat.exists

#- include: php-fpm.yml
#  when: phpfpm.stat.exists

- include: php.yml
- include: php-fpm.yml
